### ISSUE TITLE
Puedes poner un link para descargar todo?

### ISSUE THREAD

**Issue by plledo15** [juanro49/DAM#4]
Buenos días!
Un aporte fantástico!! 
Estudio bastante tiempo fuera de conexión y me gustaría poder tener todos los archivos disponibles para poder consultarlos.
Los he empezado a descargar uno a uno...pero voy a estar dos días enteros...jajajaja.
Puedes pasar un link (dropbox o lo que creas) para poder descargar todo de golpe?
Un saludo!!
plledo15@hotmail.com

**Comment by juanro49** [comment]
> Buenos días!
> Un aporte fantástico!!
> Estudio bastante tiempo fuera de conexión y me gustaría poder tener todos los archivos disponibles para poder consultarlos.
> Los he empezado a descargar uno a uno...pero voy a estar dos días enteros...jajajaja.
> Puedes pasar un link (dropbox o lo que creas) para poder descargar todo de golpe?
> Un saludo!!
> [plledo15@hotmail.com](mailto:plledo15@hotmail.com)

Hola! en la pagina principal del proyecto, puedes descargar el zip completo haciendo click  en "clone or download". Te adjunto el enlace de descarga https://github.com/juanro49/DAM/archive/master.zip

**Comment by plledo15** [comment]
OLEEE!!! Muchas gracias!
